export default {
    global: [
        'default',
        'InitialBlueprints',
        'SectorRange',
        'LaunchOffsets',
        'Scene',
        'Name',
        'MoveScript',
        'TurretPos',
        'sfx_destroy',
        'CanTargetBS',
        'Model',
        'ImpactFX',
        'launch_sfx',
        'LaunchFX',
        'sfx_volume',
        'sfx_placed',
        'sfx_spawn',
        'MaxRotateSpeedAchieveSecFP',
        'SortLayer',
        'OBB',
        'PushLayer',
        'impact_sfx',
        'DirectWeaponModel',
        'CustomEffect',
        'MaxRotateSpeedFP',
    ],
    inDefault: [
        'TID',
        'TID_DESCR',
        'Icon',
        'Name',
    ],
};
