// noinspection SpellCheckingInspection

export default {
    // Zone: '',
    // FriendlySpawns: '',
    // EnemySpawns: '',
    // InitialBlueprints: '',
    // UnlockBlueprints: '',
    // CreditsCost: '',
    CooldownMs: 'TID_BS_ABILITY_COOLDOWN',
    // HydrogenCost: '',
    // SectorRange: '',
    // SortLayer: '',
    // Radius: '',
    MaxHealth: 'TID_MODULE_STAT_HP',
    MaxForwardSpeed: 'TID_MODULE_STAT_MAX_SPEED', // TID_MODULE_STAT_SPEED
    // MaxForwardSpeedAchieveSecFP: '',
    // TargetInRangeDecelerateFactor: '',
    // MaxRotateSpeedFP: '',
    // MaxRotateSpeedAchieveSecFP: '',
    // SpeedWhenFacingAwayFromTarget: '',
    // FacingAwayFromTargetAngle: '',
    // StartReducingRotateSpeedAngle: '',
    // PrimaryWeapon: '',
    // FighterSpawnMs: '',
    NumSpawnedFighters: 'TID_MODULE_STAT_NUM_FIGHTERS',
    Rarity: 'TID_MODULE_RARITY',
    Damage: 'TID_MODULE_STAT_DPS',
    FiringRange: 'TID_MODULE_STAT_WEAPON_RANGE',
    // TargetsBS: '',
    // OBB: '',
    LifetimeMs: 'TID_MODULE_STAT_LIFETIME',
    // PushLayer: '',
    // DamagePerSecOrOneOff: '',
    // UpdateAffectedObjectsPeriodMs: '',
    // TargetsFighters: '',
    // TargetFriendly: '',
    // InitializeTimeMs: '',
    // TargetEnemy: '',
    // DamageFactorVsBS: '',
    // InitializeTimeMinMs: '',
    // InitializeTimePer1kDistanceMs: '',
    // ShipSpawned: '',
    // ShipSpawnPeriodMs: '',
    // CustomEffect: '',
    // CustomEffectStrength: '',
    // HydroBoostMs: '',
    // HydroAmtFP: '',
    // SelfDestructDamage: '',
    // DartSpeedStagesMs: '',
    // DartSpeeds: '',
    // NewGroupPerBS: '',
    // SecondaryWeapon: '',
};
